name: Echo 
on:
  push:
    branches: [ 'main' ]
jobs:
  echo:
    environment: development
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "hello github, I'm ${{github.actor}}."
      - name: echo envs
        run: | 
          echo "${{vars.dev}}"